version: '3'

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=rpsonline
      - POSTGRES_USER=rpsonline
      - POSTGRES_PASSWORD=rpsonline
  redis:
    image: redis
  web:
    entrypoint: /code/entrypoint.sh
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis