# Generated by Django 3.1 on 2020-09-08 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='creator_move',
            field=models.CharField(blank=True, choices=[('R', 'Rock'), ('P', 'Paper'), ('S', 'Scissors'), ('N', 'Nothing')], max_length=15),
        ),
        migrations.AlterField(
            model_name='game',
            name='opponent_move',
            field=models.CharField(blank=True, choices=[('R', 'Rock'), ('P', 'Paper'), ('S', 'Scissors'), ('N', 'Nothing')], max_length=15),
        ),
    ]
